pipeline {
    agent any

    stages {
        stage( 'without docker') {
            steps {
                sh '''
                    echo " without docker"
                    ls -la
                    touch container-no.txt
                   '''
            }
        }
         stage ('with docker') {
            agent{
                docker {
                    image 'nginx:latest'
                    reuseNode true // to run this in the same node
                }
            }
            steps {
                sh '''
                echo "with docker"
                ls -la
                touch container-yes.txt
                '''

            }
         }
    }
}
